description: >
  Verify semantic-release configuration file exists

parameters:
  config_file:
    default: ".releaserc.json"
    description: Configuration file those existence should be checked
    type: string

steps:
  - run:
      name: Verify configuration file exists
      command: <<include(scripts/verify-config.sh)>>
      environment:
        PARAM_SEMANTIC_RELEASERC_CONFIG_FILE: <<parameters.config_file>>
