description: >
  Install and run semantic-release with changelog configuration

executor: default

parameters:
  tag_format:
    default: \${version}
    description: Tag format (make sure to escape dollar signs)
    type: string

steps:
  - checkout
  - install
  - create_changelog_config_github:
      tag_format: <<parameters.tag_format>>
  - execute
