description: >
  Default executor using node 19.7

docker:
  - image: 'cimg/node:<<parameters.tag>>'

parameters:
  tag:
    # renovate: datasource=docker depName=cimg/node versioning=docker
    default: "20.9"
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
