description: >
  Default executor using node 19.7

docker:
  - image: 'cimg/node:<<parameters.tag>>'

parameters:
  tag:
    default: "19.7"
    description: >
      Pick a specific circleci/node image variant:
      https://hub.docker.com/r/cimg/node/tags
    type: string
